### ISSUE TITLE
Support for >1 language packs (with fatal bugs)

### ISSUE THREAD

**Issue by MrTumi** [PippleCultist/HoloCureLanguagePackMod#1]
Opening an issue not because I want to use multiple language packs at once, but because I ran into a multitude of fatal problems with just one language pack installed that must be fixed so that future support for multiple language packs can be implemented properly.

Steps to reproduce the following issues:
1. Create a language pack (Content after the first line does not matter - note that the .ttf filename in the first line is case-sensitive)
2. Open HoloCure and Navigate to Settings \ Language
3. [For errors 2.-3.] Choose the custom language

Error 1. Reproduced when trying to select the language to the right of the custom language pack (by pressing right (D) once more) (i.e. returning to the start of the circular list)
___________________________________________
############################################################################################
ERROR in
action number 1
of Draw Event
for object obj_Options:

index out of bounds request 4 maximum size is 4############################################################################################
gml_Object_obj_Options_Draw_64 (line 83)
___________________________________________
Error 2. Reproduced when the first line of the custom language pack is "NONE", and trying to confirm the selection of the custom language pack (i.e. pressing Space/Enter)
___________________________________________
############################################################################################
ERROR in
action number 1
of Draw Event
for object obj_Options:

(null) argument 1 incorrect type (undefined) expecting a Number (YYGI32)############################################################################################
gml_Script_commandPromps (line 20)
gml_Object_obj_Options_Draw_64 (line 18)
___________________________________________
Error 3. Reproduced after selecting the custom language pack in the previous launch or manually (Upon successful selection, the CurrentLanguage parameter in the local config file located at (User directory)\AppData\Local\HoloCure will be changed to the name of the custom language pack)
___________________________________________
############################################################################################
ERROR in
action number 1
of Draw Event
for object obj_Pre_Intro:

trying to index a variable which is not an array############################################################################################
gml_Object_obj_Pre_Intro_Draw_0 (line 6)
___________________________________________
[Remarks: This can be fixed by manually reverting the CurrentLanguage parameter in the local config file to one of the three officially supported languages such as "eng" (for English. If one runs into this error, the game will never launch successfully unless this fix is applied, even reinstallations of the mod or even the game doesn't fix the issue!]

**Comment by PippleCultist** [comment]
Thanks for the detailed bug report. I fixed the issues in v1.0.1, so let me know if you encounter any other issues. Also, I had to remove saving the currently used custom language pack to the config file since the game starts running before the mod finishes loading which was causing the crash. I'll look further into it to see if I can find any workaround for that.

**Comment by MrTumi** [comment]
Thanks for the quick fix!!
