### ISSUE TITLE
Mod does not work on 0.7 update

### ISSUE THREAD

**Issue by 1benkei1** [PippleCultist/HoloCureLanguagePackMod#14]
After the release of the new version, the game does not start. 

If you just launch the game after the update, a message appears in the log and the game does not start.
![Безымянный](https://github.com/user-attachments/assets/2dc7070b-212b-4cc1-8d37-923379d95b48)

However, if you reinstall aurie after that, the log is shown longer, but still does not start the game.
![1](https://github.com/user-attachments/assets/7924116c-d930-4bcf-adba-1b67936d5cb9)

After that, I decided to completely delete all the mod files (aurie too) and reinstall the game itself. The game did not start again. An error appeared "Failed to start game" on steam. Sorry, the screenshot was not saved. "Verify Integrity of Game Cache"did not help. So I downloaded game from itch io and replaced the files. Now the game is starting, but it took much longer to run than the rest of the games on steam. At the same time it works even after you delete the game and download it again from steam. It's strange, but i can play.

If after all this you just install aurie and do not add the mod files, then this appears in the log:
![2](https://github.com/user-attachments/assets/a4ca5ac3-9986-4970-93e0-45d0445c695a)
It takes a long time, but the game starts.

**Comment by PippleCultist** [comment]
I'm currently working on fixing the mod so that it works in 0.7.

**Comment by PippleCultist** [comment]
v1.0.8 is now working with 0.7, but parts of your existing language pack is going to cause the game to crash because the dev has changed the text for several parts to different type (Eg. MuscleDescription should now be an array).
