### ISSUE TITLE
Errors with 1.0.8 mod ver on 0.7 holocure

### ISSUE THREAD

**Issue by XAXAHOT** [PippleCultist/HoloCureLanguagePackMod#15]
Updated the mod manager, updated the mod, but when launched it gives an error
![image](https://github.com/user-attachments/assets/b89c93f5-cede-4730-8465-75844dc19572)
![image](https://github.com/user-attachments/assets/149fde88-d2e8-42e3-b50a-298136d95a5f)
![image](https://github.com/user-attachments/assets/3f536ac5-76e6-47fc-b1c9-de0b410ce8e5)

**Comment by PippleCultist** [comment]
This is an issue with YYTK. You'll need to wait until it updates with the fix
