### ISSUE TITLE
The game crashes

### ISSUE THREAD

**Issue by 1benkei1** [PippleCultist/HoloCureLanguagePackMod#2]
When getting Subaru's skills, the game crashes. 
During the level increases, a selection of items and skills appears on the screen. If skill (Sunny Optimism or Oozora Police) is present in this list, then the game crashes.
![Снимок](https://github.com/PippleCultist/HoloCureLanguagePackMod/assets/165812068/3f08b9a3-0481-44cb-828c-11a39f6708e1)

**Comment by 1benkei1** [comment]
I suspect that the problem is [c_cyan], since if you put a different color, then everything works. I don't know why

**Comment by PippleCultist** [comment]
This should be fixed in v1.0.2. Let me know if you encounter any other issues.
