### ISSUE TITLE
Name of food

### ISSUE THREAD

**Issue by 1benkei1** [PippleCultist/HoloCureLanguagePackMod#3]
The name of the food is not loaded onto the stage selection screen from the language pack. But if you go into Holo House first, and only then go to the stage selection screen, then name of food will load.
![1](https://github.com/PippleCultist/HoloCureLanguagePackMod/assets/165812068/4ba912dd-8f7c-4f4a-a4c1-3059a061d067)
![2](https://github.com/PippleCultist/HoloCureLanguagePackMod/assets/165812068/839a2fe9-df33-485b-920b-79497eb79599)

**Comment by PippleCultist** [comment]
This issue should be fixed in v1.0.3. Let me know if you encounter any other issues.
