### ISSUE TITLE
LV Manager

### ISSUE THREAD

**Issue by 1benkei1** [PippleCultist/HoloCureLanguagePackMod#4]
Manger LV (number) is not displayed.
![Снимок](https://github.com/PippleCultist/HoloCureLanguagePackMod/assets/165812068/5462bc21-0a98-49cc-b9e6-107f1583a75e)

**Comment by PippleCultist** [comment]
Sorry, but I couldn't replicate the issue. Can you give more details on how this issue is happening? Also, it's weird that only the manager level is not showing up, but the other numbers are.

**Comment by 1benkei1** [comment]
The screenshot shows exactly the lv 3. Maybe the problem is exactly in 3? Unfortunately, I can't check the rest of the levels. I also use a different font for my localization, not the standard one. Due to the peculiarities of my language, a more compact font is needed, so i was chose faks10Dev1 . However, there were no problems with other numbers.

**Comment by PippleCultist** [comment]
This issue is fixed in v1.0.5
