### ISSUE TITLE
hiscoreButtons

### ISSUE THREAD

**Issue by 1benkei1** [PippleCultist/HoloCureLanguagePackMod#5]
The buttons on the Leaderboard do not change. There are no bugs, but there are no changes either. For example, here I have inserted the Indonesian language of these buttons into my language file, but there are no changes.
![Снимок](https://github.com/PippleCultist/HoloCureLanguagePackMod/assets/165812068/8c72404c-74b9-47ee-9382-39e7e5d0a97f)
Eng: hiscoreButtons ["", "Select Board", "[ "ALL TIME","DAILY" ]", "Next", "Previous", "My Score", "Quit"]
Id: hiscoreButtons  ["", "Pilih Papan", "[ "SETIAP WAKTU","HARIAN" ]", "Berikutnya", "Sebelumnya", "Skor Ku", "Keluar"] (as an example)
ru: hiscoreButtons  ["", "Выбор", "["ЗА ВСЁ ВРЕМЯ","ЗА СЕГОДНЯ"]", "Далее", "Назад", "Мой Счёт", "Выход"] (What do I need)

**Comment by PippleCultist** [comment]
This has been fixed in v1.0.4.
