### ISSUE TITLE
Missing Text

### ISSUE THREAD

**Issue by 1benkei1** [PippleCultist/HoloCureLanguagePackMod#6]
The file "TextContainer" is missing some text that is in the game. below I will give all the examples that I found. These are not textures, but text.
"CONFIRM: SPACE/ENTER | CANCEL: SHIFT/ESC"
Location - in the lower right corner of the screen, in almost any window.
![1](https://github.com/PippleCultist/HoloCureLanguagePackMod/assets/165812068/bc6a440b-b315-452d-9fb2-15492d583ffe)

"ACHIEVEMENTS"
Location - button "Achievements" on the main screen. This word will be on top.
![2](https://github.com/PippleCultist/HoloCureLanguagePackMod/assets/165812068/d67655fa-3afc-445d-9359-4bf040808dcd)

"Anonymous" "Score" "TIME" "LV" "Rank"
Location - button "Leaderbord" on the main screen. Тhis is the data of the players.
![3](https://github.com/PippleCultist/HoloCureLanguagePackMod/assets/165812068/7636bb62-f4f3-4249-9603-5a7f5594d5ed)

"ALL TIME"
Location - button "Leaderbord" on the main screen. This word will be on top.
![4](https://github.com/PippleCultist/HoloCureLanguagePackMod/assets/165812068/6281fc1b-9e5c-46cb-bd38-e64492383423)

"DAILY"
Location - button "Leaderbord" on the main screen. This word will be on top, but first need to select "Daily" on the button on the right.
![5](https://github.com/PippleCultist/HoloCureLanguagePackMod/assets/165812068/000368fd-a6fc-4e86-beef-67165b7de892)

"COST"
Location -  button "Shop" on the main screen. Then "Charter Gacha" - click on the banner - "Tears Menu". The word will be on the banner.
![6](https://github.com/PippleCultist/HoloCureLanguagePackMod/assets/165812068/511e2cd5-783e-43ae-a361-210c9bfdbba1)

"SHOOSE YOUR IDOL"
Location - On top of the character selection screen.
![7](https://github.com/PippleCultist/HoloCureLanguagePackMod/assets/165812068/aa383bbd-f8d2-434b-a732-537c46e8344a)

"CHOOSE MODE"
Location - On the mod selection screen.
![8](https://github.com/PippleCultist/HoloCureLanguagePackMod/assets/165812068/f786d6c5-cbd7-4e9b-9e64-d9029a0c5308)

"CHOOSE STAGE" "STAGE 1, 2, 3... etc" "HoloCoin"
Location - On the stage selection screen.
![9](https://github.com/PippleCultist/HoloCureLanguagePackMod/assets/165812068/b3283b80-b59b-44f5-8069-f5e6cb21b6d5)

"HP" "ATK" "SPD" "CRT"
Location - On top of the character selection screen.
![10](https://github.com/PippleCultist/HoloCureLanguagePackMod/assets/165812068/8fe100ae-e339-4329-99d8-2b0a73d8ab79)

"LEVEL UP!" "HP" "ATK" "SPD" "CRT" "Pickup" "Haste"
Location - during the game, if level up or pause the game.
![11](https://github.com/PippleCultist/HoloCureLanguagePackMod/assets/165812068/30424b82-6009-42c6-bc66-5b19f038f6b5)

"STAGE" "SKILLS"
Location - "STAGE" the top of the screen during the game, and "SKILLS" in the skills menu during the game.
![12](https://github.com/PippleCultist/HoloCureLanguagePackMod/assets/165812068/3bbd86be-4169-45f9-b926-689b4dbfe462)

"PAUSED"
Location - it will appear if pause the game.
![13](https://github.com/PippleCultist/HoloCureLanguagePackMod/assets/165812068/75def54a-c0a1-4996-b7cc-649393dffc24)

"QUIT?"
Location - it will appear if you press the "Quit" button during a pause.
![14](https://github.com/PippleCultist/HoloCureLanguagePackMod/assets/165812068/af07dc1b-772a-408b-a52d-c33f745cf0ba)

"HOLO HOUSE"
Location - select "Holo House" in the main menu, and then select a character.
![15](https://github.com/PippleCultist/HoloCureLanguagePackMod/assets/165812068/c2e2204d-68a1-4b34-9dbc-32ee50181b36)

"ENDLESS"
Location - the top of the screen while playing in endless mode.
![18](https://github.com/PippleCultist/HoloCureLanguagePackMod/assets/165812068/48f86bcb-c5b9-4764-9f8d-e4aca5269144)

"TIME STAGE" "BEST TIME"
Location - It will appear if you select "TIME MODE" on the mode selection screen.
![19](https://github.com/PippleCultist/HoloCureLanguagePackMod/assets/165812068/5771d7cb-396a-4832-9b74-56913ce14382)

"TIME" "Remaining:"
Location - the top of the screen while playing in time mode.
![20](https://github.com/PippleCultist/HoloCureLanguagePackMod/assets/165812068/716aeec5-aae1-4239-bef1-64b46552d0dd)

"GAME OVER" "HoloCoins Gained:"
Location - it will appear if lose the game
![21](https://github.com/PippleCultist/HoloCureLanguagePackMod/assets/165812068/cafeee40-d84d-4720-8788-be5e695b6773)

**Comment by 1benkei1** [comment]
"Weapon" "Skill" "Item"
Location - A level-up screen where we select improvements during run
![Снимок](https://github.com/PippleCultist/HoloCureLanguagePackMod/assets/165812068/d6b80ca5-6e30-4750-be9d-fc7515662730)

**Comment by PippleCultist** [comment]
I have added a direct mapping feature in v1.0.4 which should let you get around this issue. Unfortunately, it has to be an exact match of what text you want to replace, and there's no good way to get that exact text since the text is hard coded. Also, just letting you know that the `confirm: ` and `cancel: ` are in the text container under mainButtons.
