### ISSUE TITLE
The numbers are missing

### ISSUE THREAD

**Issue by 1benkei1** [PippleCultist/HoloCureLanguagePackMod#8]
After the last update, the numbers of coins and sand disappeared. Although they used to be.
![2](https://github.com/PippleCultist/HoloCureLanguagePackMod/assets/165812068/2a11f677-0f59-45cc-b20b-f37d78dac996)
![Снимок](https://github.com/PippleCultist/HoloCureLanguagePackMod/assets/165812068/6f77071d-945f-4b14-9f6a-fbeced2f2bc8)

![1](https://github.com/PippleCultist/HoloCureLanguagePackMod/assets/165812068/79729e2b-f5b3-4561-9ae5-727af4943d25)

**Comment by PippleCultist** [comment]
I can't replicate it on my side. Can you send over the ttf file you're using and a minimal language pack that still causes the error you're seeing?

**Comment by 1benkei1** [comment]
[Palata_3.zip](https://github.com/PippleCultist/HoloCureLanguagePackMod/files/15495891/Palata_3.zip)

**Comment by 1benkei1** [comment]
I didn't know it was possible to send zip-files here. Sorry for the delay

**Comment by PippleCultist** [comment]
This issue is now fixed in v1.0.5.
