### ISSUE TITLE
Problem with \n

### ISSUE THREAD

**Issue by 1benkei1** [PippleCultist/HoloCureLanguagePackMod#9]
When using \n, a large indentation appears, which should not be there. Here is an example of Sana's "Gravity" skill
![Снимок](https://github.com/PippleCultist/HoloCureLanguagePackMod/assets/165812068/c0f82767-8f1a-4a38-95a1-84e88854bb68)
GravityDescription ["Каждые 5 секунд создается гравитационный взрыв, наносящий [c_green]125%[/color] урона. Сам урон также увеличивается\nза счёт эффектов увеличения площади."]

**Comment by 1benkei1** [comment]
But on the credits screen, it is ok
![Снимок](https://github.com/PippleCultist/HoloCureLanguagePackMod/assets/165812068/41d7e747-e694-4815-bf30-d17e1a6b2339)

**Comment by 1benkei1** [comment]
on the "Fandoms" screen, this function does not work at all
![Снимок](https://github.com/user-attachments/assets/4114cc6c-2d87-4f8f-a567-924e814942ee)

fandomTexts ["Фэндом: ", "Бонусы: ", "Получение Опыта:\n[c_yellow]-Завершите Этап или проведите 30 минут в Бесконечном Режиме:[/color]\n[c_yellow]Нормально: 7 Опыта [/color]   [c_white]За первый раз 14 Опыта[/color]\n[c_yellow]Сложно: 10 Опыта [/color]   [c_white]За первый раз 20 Опыта[/color]\n[c_yellow]-Повышение G. Ранга: 2 Опыта[/color]   [c_white](Максимум 20 раз)[/color]"]

**Comment by XAXAHOT** [comment]
Same problem, i'm think this happen by colored text, if remove [*color*][/color] - its working good

BubbaDescription ["Получает пса-компаньона, который атакует случайные\nцели. Каждое попадание наносит 100% от вашего\nбазавого урона.", ...]
![image](https://github.com/user-attachments/assets/2c60ad78-ab4a-4dca-bc57-fa2e20fce253)

BubbaDescription ["Получает пса-компаньона, который атакует случайные\nцели. Каждое попадание наносит [c_green]100%[/color] от вашего\nбазавого урона.", ...]
![image](https://github.com/user-attachments/assets/31362526-1990-4fe8-bbf5-d9e9c909c3fd)

**Comment by PippleCultist** [comment]
Issue is now fixed in v1.0.6
